ALTER TABLE IF EXISTS projects RENAME COLUMN location TO address;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS country TEXT;